/*
 * Earmark signal-contract constants.
 *
 * GENERATED by contract/codegen.py from contract/signal.yaml. DO NOT EDIT.
 * Regenerate with `make codegen`; `make contract-check` fails when this file is stale.
 *
 * The EARMARK_* macros are usable from C (the earmark.h ABI); C++ code should use
 * the typed constants in namespace earmark::contract.
 */
#ifndef EARMARK_CONSTANTS_H_
#define EARMARK_CONSTANTS_H_

/* Schema version of contract/signal.yaml. */
#define EARMARK_CONTRACT_VERSION 1
/* SHA-256 prefix of every other constant; stamp it into weight manifests and goldens. */
#define EARMARK_CONTRACT_HASH "875b5abc86eafabb"
/* Internal model sample rate in Hz. */
#define EARMARK_SAMPLE_RATE 16000
/* Channel count at the model boundary (mono). */
#define EARMARK_NUM_CHANNELS 1
/* Analysis and synthesis window: w[n] = sin(pi * n / WINDOW_LENGTH), n in [0, WINDOW_LENGTH). */
#define EARMARK_WINDOW "sqrt_hann_periodic"
/* WOLA window length in samples. */
#define EARMARK_WINDOW_LENGTH 320
/* WOLA hop in samples; one model step per hop. */
#define EARMARK_HOP_LENGTH 160
/* FFT size in samples. */
#define EARMARK_N_FFT 320
/* One-sided STFT bins, N_FFT // 2 + 1. */
#define EARMARK_N_BINS 161
/* Forward DFT unscaled, inverse DFT scaled by 1 / N_FFT. */
#define EARMARK_FFT_NORM "backward"
/* False: frame t covers samples [t * HOP_LENGTH, t * HOP_LENGTH + WINDOW_LENGTH). */
#define EARMARK_STFT_CENTER 0
/* Hop duration in milliseconds. */
#define EARMARK_HOP_MS 10
/* Window duration in milliseconds. */
#define EARMARK_WINDOW_MS 20
/* Model frames (hops) per second. */
#define EARMARK_FRAME_RATE_HZ 100
/* Algorithmic latency in milliseconds. */
#define EARMARK_ALGORITHMIC_LATENCY_MS 20
/* Algorithmic latency in samples: WINDOW_LENGTH + LOOKAHEAD_FRAMES * HOP_LENGTH. */
#define EARMARK_ALGORITHMIC_LATENCY_SAMPLES 320
/* Future frames the model may see (zero). */
#define EARMARK_LOOKAHEAD_FRAMES 0
/* Number of ERB bands for gains and log-power features. */
#define EARMARK_ERB_BANDS 32
/* Minimum STFT bins per ERB band. */
#define EARMARK_ERB_MIN_BINS 2
/* STFT bins per ERB band, low to high; contiguous and summing to N_BINS. */
#define EARMARK_ERB_WIDTHS_COUNT 32
#define EARMARK_ERB_WIDTHS_INIT { \
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, \
    2, 2, 2, 2, 3, 6, 7, 7, 8, 8, 10, 12, 12, 14, 16, 18, \
}
/* Deep-filter taps per bin (current and previous frames). */
#define EARMARK_DF_ORDER 3
/* Deep filter applies to STFT bins [0, DF_BINS). */
#define EARMARK_DF_BINS 64
/* Future frames used by the deep filter. */
#define EARMARK_DF_LOOKAHEAD_FRAMES 0
/* Feature normalisation: causal exponential moving mean. */
#define EARMARK_NORM_KIND "causal_exponential_mean"
/* Normalisation time constant in seconds. */
#define EARMARK_NORM_TAU_S 1.0
/* Per-hop decay exp(-HOP_LENGTH / (SAMPLE_RATE * NORM_TAU_S)): m = a * m + (1 - a) * x. */
#define EARMARK_NORM_ALPHA 0.9900498337491681
/* Speaker-embedding dimension. */
#define EARMARK_EMBEDDING_DIM 256
/* VAD label threshold reference level. */
#define EARMARK_VAD_REFERENCE "utterance_peak"
/* Frame is target-active when direct-path energy exceeds the peak by this many dB. */
#define EARMARK_VAD_THRESHOLD_DB (-40.0)
/* VAD label hangover in milliseconds. */
#define EARMARK_VAD_HANGOVER_MS 50
/* VAD label hangover in frames. */
#define EARMARK_VAD_HANGOVER_FRAMES 5
/* Barge-in onset: minimum activity in ms. */
#define EARMARK_BARGEIN_MIN_ACTIVE_MS 200
/* Barge-in onset: minimum activity in frames. */
#define EARMARK_BARGEIN_MIN_ACTIVE_FRAMES 20
/* Barge-in onset: minimum preceding silence in ms. */
#define EARMARK_BARGEIN_MIN_SILENCE_MS 300
/* Barge-in onset: minimum preceding silence in frames. */
#define EARMARK_BARGEIN_MIN_SILENCE_FRAMES 30

#ifdef __cplusplus

#include <array>
#include <cstddef>
#include <string_view>

namespace earmark::contract {

/** Schema version of contract/signal.yaml. */
inline constexpr int CONTRACT_VERSION = EARMARK_CONTRACT_VERSION;
/** SHA-256 prefix of every other constant; stamp it into weight manifests and goldens. */
inline constexpr std::string_view CONTRACT_HASH = EARMARK_CONTRACT_HASH;
/** Internal model sample rate in Hz. */
inline constexpr int SAMPLE_RATE = EARMARK_SAMPLE_RATE;
/** Channel count at the model boundary (mono). */
inline constexpr int NUM_CHANNELS = EARMARK_NUM_CHANNELS;
/** Analysis and synthesis window: w[n] = sin(pi * n / WINDOW_LENGTH), n in [0, WINDOW_LENGTH). */
inline constexpr std::string_view WINDOW = EARMARK_WINDOW;
/** WOLA window length in samples. */
inline constexpr int WINDOW_LENGTH = EARMARK_WINDOW_LENGTH;
/** WOLA hop in samples; one model step per hop. */
inline constexpr int HOP_LENGTH = EARMARK_HOP_LENGTH;
/** FFT size in samples. */
inline constexpr int N_FFT = EARMARK_N_FFT;
/** One-sided STFT bins, N_FFT // 2 + 1. */
inline constexpr int N_BINS = EARMARK_N_BINS;
/** Forward DFT unscaled, inverse DFT scaled by 1 / N_FFT. */
inline constexpr std::string_view FFT_NORM = EARMARK_FFT_NORM;
/** False: frame t covers samples [t * HOP_LENGTH, t * HOP_LENGTH + WINDOW_LENGTH). */
inline constexpr bool STFT_CENTER = EARMARK_STFT_CENTER != 0;
/** Hop duration in milliseconds. */
inline constexpr int HOP_MS = EARMARK_HOP_MS;
/** Window duration in milliseconds. */
inline constexpr int WINDOW_MS = EARMARK_WINDOW_MS;
/** Model frames (hops) per second. */
inline constexpr int FRAME_RATE_HZ = EARMARK_FRAME_RATE_HZ;
/** Algorithmic latency in milliseconds. */
inline constexpr int ALGORITHMIC_LATENCY_MS = EARMARK_ALGORITHMIC_LATENCY_MS;
/** Algorithmic latency in samples: WINDOW_LENGTH + LOOKAHEAD_FRAMES * HOP_LENGTH. */
inline constexpr int ALGORITHMIC_LATENCY_SAMPLES = EARMARK_ALGORITHMIC_LATENCY_SAMPLES;
/** Future frames the model may see (zero). */
inline constexpr int LOOKAHEAD_FRAMES = EARMARK_LOOKAHEAD_FRAMES;
/** Number of ERB bands for gains and log-power features. */
inline constexpr int ERB_BANDS = EARMARK_ERB_BANDS;
/** Minimum STFT bins per ERB band. */
inline constexpr int ERB_MIN_BINS = EARMARK_ERB_MIN_BINS;
/** STFT bins per ERB band, low to high; contiguous and summing to N_BINS. */
inline constexpr std::array<int, EARMARK_ERB_WIDTHS_COUNT> ERB_WIDTHS = EARMARK_ERB_WIDTHS_INIT;
/** Deep-filter taps per bin (current and previous frames). */
inline constexpr int DF_ORDER = EARMARK_DF_ORDER;
/** Deep filter applies to STFT bins [0, DF_BINS). */
inline constexpr int DF_BINS = EARMARK_DF_BINS;
/** Future frames used by the deep filter. */
inline constexpr int DF_LOOKAHEAD_FRAMES = EARMARK_DF_LOOKAHEAD_FRAMES;
/** Feature normalisation: causal exponential moving mean. */
inline constexpr std::string_view NORM_KIND = EARMARK_NORM_KIND;
/** Normalisation time constant in seconds. */
inline constexpr double NORM_TAU_S = EARMARK_NORM_TAU_S;
/** Per-hop decay exp(-HOP_LENGTH / (SAMPLE_RATE * NORM_TAU_S)): m = a * m + (1 - a) * x. */
inline constexpr double NORM_ALPHA = EARMARK_NORM_ALPHA;
/** Speaker-embedding dimension. */
inline constexpr int EMBEDDING_DIM = EARMARK_EMBEDDING_DIM;
/** VAD label threshold reference level. */
inline constexpr std::string_view VAD_REFERENCE = EARMARK_VAD_REFERENCE;
/** Frame is target-active when direct-path energy exceeds the peak by this many dB. */
inline constexpr double VAD_THRESHOLD_DB = EARMARK_VAD_THRESHOLD_DB;
/** VAD label hangover in milliseconds. */
inline constexpr int VAD_HANGOVER_MS = EARMARK_VAD_HANGOVER_MS;
/** VAD label hangover in frames. */
inline constexpr int VAD_HANGOVER_FRAMES = EARMARK_VAD_HANGOVER_FRAMES;
/** Barge-in onset: minimum activity in ms. */
inline constexpr int BARGEIN_MIN_ACTIVE_MS = EARMARK_BARGEIN_MIN_ACTIVE_MS;
/** Barge-in onset: minimum activity in frames. */
inline constexpr int BARGEIN_MIN_ACTIVE_FRAMES = EARMARK_BARGEIN_MIN_ACTIVE_FRAMES;
/** Barge-in onset: minimum preceding silence in ms. */
inline constexpr int BARGEIN_MIN_SILENCE_MS = EARMARK_BARGEIN_MIN_SILENCE_MS;
/** Barge-in onset: minimum preceding silence in frames. */
inline constexpr int BARGEIN_MIN_SILENCE_FRAMES = EARMARK_BARGEIN_MIN_SILENCE_FRAMES;

namespace detail {
template <std::size_t N>
constexpr int sum(const std::array<int, N>& values) {
  int total = 0;
  for (const int v : values) total += v;
  return total;
}
}  // namespace detail

static_assert(N_BINS == N_FFT / 2 + 1, "N_BINS must be N_FFT / 2 + 1");
static_assert(2 * HOP_LENGTH == WINDOW_LENGTH, "sqrt-Hann WOLA needs 50% overlap");
static_assert(detail::sum(ERB_WIDTHS) == N_BINS, "ERB bands must cover every bin");
static_assert(static_cast<int>(ERB_WIDTHS.size()) == ERB_BANDS, "ERB band count");
static_assert(DF_BINS <= N_BINS, "deep-filter bins exceed the spectrum");

}  // namespace earmark::contract

#endif  /* __cplusplus */

#endif  /* EARMARK_CONSTANTS_H_ */
