"""Earmark signal-contract constants.

GENERATED by contract/codegen.py from contract/signal.yaml. DO NOT EDIT.
Regenerate with `make codegen`; `make contract-check` fails when this file is stale.
"""

from typing import Final

#: Schema version of contract/signal.yaml.
CONTRACT_VERSION: Final[int] = 1

#: SHA-256 prefix of every other constant; stamp it into weight manifests and goldens.
CONTRACT_HASH: Final[str] = "875b5abc86eafabb"

#: Internal model sample rate in Hz.
SAMPLE_RATE: Final[int] = 16000

#: Channel count at the model boundary (mono).
NUM_CHANNELS: Final[int] = 1

#: Analysis and synthesis window: w[n] = sin(pi * n / WINDOW_LENGTH), n in [0, WINDOW_LENGTH).
WINDOW: Final[str] = "sqrt_hann_periodic"

#: WOLA window length in samples.
WINDOW_LENGTH: Final[int] = 320

#: WOLA hop in samples; one model step per hop.
HOP_LENGTH: Final[int] = 160

#: FFT size in samples.
N_FFT: Final[int] = 320

#: One-sided STFT bins, N_FFT // 2 + 1.
N_BINS: Final[int] = 161

#: Forward DFT unscaled, inverse DFT scaled by 1 / N_FFT.
FFT_NORM: Final[str] = "backward"

#: False: frame t covers samples [t * HOP_LENGTH, t * HOP_LENGTH + WINDOW_LENGTH).
STFT_CENTER: Final[bool] = False

#: Hop duration in milliseconds.
HOP_MS: Final[int] = 10

#: Window duration in milliseconds.
WINDOW_MS: Final[int] = 20

#: Model frames (hops) per second.
FRAME_RATE_HZ: Final[int] = 100

#: Algorithmic latency in milliseconds.
ALGORITHMIC_LATENCY_MS: Final[int] = 20

#: Algorithmic latency in samples: WINDOW_LENGTH + LOOKAHEAD_FRAMES * HOP_LENGTH.
ALGORITHMIC_LATENCY_SAMPLES: Final[int] = 320

#: Future frames the model may see (zero).
LOOKAHEAD_FRAMES: Final[int] = 0

#: Number of ERB bands for gains and log-power features.
ERB_BANDS: Final[int] = 32

#: Minimum STFT bins per ERB band.
ERB_MIN_BINS: Final[int] = 2

#: STFT bins per ERB band, low to high; contiguous and summing to N_BINS.
ERB_WIDTHS: Final[tuple[int, ...]] = (
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 3, 6, 7, 7, 8, 8, 10, 12, 12, 14, 16, 18,
)

#: Deep-filter taps per bin (current and previous frames).
DF_ORDER: Final[int] = 3

#: Deep filter applies to STFT bins [0, DF_BINS).
DF_BINS: Final[int] = 64

#: Future frames used by the deep filter.
DF_LOOKAHEAD_FRAMES: Final[int] = 0

#: Feature normalisation: causal exponential moving mean.
NORM_KIND: Final[str] = "causal_exponential_mean"

#: Normalisation time constant in seconds.
NORM_TAU_S: Final[float] = 1.0

#: Per-hop decay exp(-HOP_LENGTH / (SAMPLE_RATE * NORM_TAU_S)): m = a * m + (1 - a) * x.
NORM_ALPHA: Final[float] = 0.9900498337491681

#: Speaker-embedding dimension.
EMBEDDING_DIM: Final[int] = 256

#: VAD label threshold reference level.
VAD_REFERENCE: Final[str] = "utterance_peak"

#: Frame is target-active when direct-path energy exceeds the peak by this many dB.
VAD_THRESHOLD_DB: Final[float] = -40.0

#: VAD label hangover in milliseconds.
VAD_HANGOVER_MS: Final[int] = 50

#: VAD label hangover in frames.
VAD_HANGOVER_FRAMES: Final[int] = 5

#: Barge-in onset: minimum activity in ms.
BARGEIN_MIN_ACTIVE_MS: Final[int] = 200

#: Barge-in onset: minimum activity in frames.
BARGEIN_MIN_ACTIVE_FRAMES: Final[int] = 20

#: Barge-in onset: minimum preceding silence in ms.
BARGEIN_MIN_SILENCE_MS: Final[int] = 300

#: Barge-in onset: minimum preceding silence in frames.
BARGEIN_MIN_SILENCE_FRAMES: Final[int] = 30

__all__ = [
    "CONTRACT_VERSION",
    "CONTRACT_HASH",
    "SAMPLE_RATE",
    "NUM_CHANNELS",
    "WINDOW",
    "WINDOW_LENGTH",
    "HOP_LENGTH",
    "N_FFT",
    "N_BINS",
    "FFT_NORM",
    "STFT_CENTER",
    "HOP_MS",
    "WINDOW_MS",
    "FRAME_RATE_HZ",
    "ALGORITHMIC_LATENCY_MS",
    "ALGORITHMIC_LATENCY_SAMPLES",
    "LOOKAHEAD_FRAMES",
    "ERB_BANDS",
    "ERB_MIN_BINS",
    "ERB_WIDTHS",
    "DF_ORDER",
    "DF_BINS",
    "DF_LOOKAHEAD_FRAMES",
    "NORM_KIND",
    "NORM_TAU_S",
    "NORM_ALPHA",
    "EMBEDDING_DIM",
    "VAD_REFERENCE",
    "VAD_THRESHOLD_DB",
    "VAD_HANGOVER_MS",
    "VAD_HANGOVER_FRAMES",
    "BARGEIN_MIN_ACTIVE_MS",
    "BARGEIN_MIN_ACTIVE_FRAMES",
    "BARGEIN_MIN_SILENCE_MS",
    "BARGEIN_MIN_SILENCE_FRAMES",
]
