/**
 * Earmark signal-contract constants.
 *
 * GENERATED by contract/codegen.py from contract/signal.yaml. DO NOT EDIT.
 * Regenerate with `make codegen`; `make contract-check` fails when this file is stale.
 */

/** Schema version of contract/signal.yaml. */
export const CONTRACT_VERSION = 1;
/** SHA-256 prefix of every other constant; stamp it into weight manifests and goldens. */
export const CONTRACT_HASH = "875b5abc86eafabb";
/** Internal model sample rate in Hz. */
export const SAMPLE_RATE = 16000;
/** Channel count at the model boundary (mono). */
export const NUM_CHANNELS = 1;
/** Analysis and synthesis window: w[n] = sin(pi * n / WINDOW_LENGTH), n in [0, WINDOW_LENGTH). */
export const WINDOW = "sqrt_hann_periodic";
/** WOLA window length in samples. */
export const WINDOW_LENGTH = 320;
/** WOLA hop in samples; one model step per hop. */
export const HOP_LENGTH = 160;
/** FFT size in samples. */
export const N_FFT = 320;
/** One-sided STFT bins, N_FFT // 2 + 1. */
export const N_BINS = 161;
/** Forward DFT unscaled, inverse DFT scaled by 1 / N_FFT. */
export const FFT_NORM = "backward";
/** False: frame t covers samples [t * HOP_LENGTH, t * HOP_LENGTH + WINDOW_LENGTH). */
export const STFT_CENTER = false;
/** Hop duration in milliseconds. */
export const HOP_MS = 10;
/** Window duration in milliseconds. */
export const WINDOW_MS = 20;
/** Model frames (hops) per second. */
export const FRAME_RATE_HZ = 100;
/** Algorithmic latency in milliseconds. */
export const ALGORITHMIC_LATENCY_MS = 20;
/** Algorithmic latency in samples: WINDOW_LENGTH + LOOKAHEAD_FRAMES * HOP_LENGTH. */
export const ALGORITHMIC_LATENCY_SAMPLES = 320;
/** Future frames the model may see (zero). */
export const LOOKAHEAD_FRAMES = 0;
/** Number of ERB bands for gains and log-power features. */
export const ERB_BANDS = 32;
/** Minimum STFT bins per ERB band. */
export const ERB_MIN_BINS = 2;
/** STFT bins per ERB band, low to high; contiguous and summing to N_BINS. */
export const ERB_WIDTHS = Object.freeze([
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 3, 6, 7, 7, 8, 8, 10, 12, 12, 14, 16, 18,
]);
/** Deep-filter taps per bin (current and previous frames). */
export const DF_ORDER = 3;
/** Deep filter applies to STFT bins [0, DF_BINS). */
export const DF_BINS = 64;
/** Future frames used by the deep filter. */
export const DF_LOOKAHEAD_FRAMES = 0;
/** Feature normalisation: causal exponential moving mean. */
export const NORM_KIND = "causal_exponential_mean";
/** Normalisation time constant in seconds. */
export const NORM_TAU_S = 1.0;
/** Per-hop decay exp(-HOP_LENGTH / (SAMPLE_RATE * NORM_TAU_S)): m = a * m + (1 - a) * x. */
export const NORM_ALPHA = 0.9900498337491681;
/** Speaker-embedding dimension. */
export const EMBEDDING_DIM = 256;
/** VAD label threshold reference level. */
export const VAD_REFERENCE = "utterance_peak";
/** Frame is target-active when direct-path energy exceeds the peak by this many dB. */
export const VAD_THRESHOLD_DB = -40.0;
/** VAD label hangover in milliseconds. */
export const VAD_HANGOVER_MS = 50;
/** VAD label hangover in frames. */
export const VAD_HANGOVER_FRAMES = 5;
/** Barge-in onset: minimum activity in ms. */
export const BARGEIN_MIN_ACTIVE_MS = 200;
/** Barge-in onset: minimum activity in frames. */
export const BARGEIN_MIN_ACTIVE_FRAMES = 20;
/** Barge-in onset: minimum preceding silence in ms. */
export const BARGEIN_MIN_SILENCE_MS = 300;
/** Barge-in onset: minimum preceding silence in frames. */
export const BARGEIN_MIN_SILENCE_FRAMES = 30;
